### DISCUSSION TITLE
Is it possible to export data prior to the SHUTDOWN event?

### DISCUSSION THREAD

**Discussion by raresgmihalcea** [open-telemetry/opentelemetry-lambda#1137] [Q&A]
Hi! Considering the following config, I would expect the collector layer to:
 - Batch all the data received in a 10-second window
 - Send data to the remote write URL _as soon as the processors are done_
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 'localhost:4318'

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "https://bnhtiptgy5.execute-api.eu-west-1.amazonaws.com/default/dummy-function"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite,logging]
```
However, the actual behavior is that the data is only being pushed when the SHUTDOWN event is received. 

Am I missing something, or is the desired behavior not achievable?
