### DISCUSSION TITLE
How can I change Service Name?

### DISCUSSION THREAD

**Discussion by tarek-sater-pf** [open-telemetry/opentelemetry-lambda#1832] [Q&A] [answered]
Hi

I'm receiving logs with OTLP but `service_name = <function_name>`. It seems to be hardcoded to be the Lambda function name.

I tried setting OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES and manual instrumentation via ATTR_SERVICE_NAME, but still I only get the function name.

Is there any way to set it?

**Comment by tylerbenson** [comment]
I don't think it's consistent between languages.  Which language?

Here's an example of how this is implemented for Nodejs: https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/packages/layer/scripts/otel-handler#L7

**Reply by tarek-sater-pf** [reply]
Nodejs. It didnt work when I set `OTEL_RESOURCE_ATTRIBUTES`

**Reply by tarek-sater-pf** [reply]
To be clear, it doesn't work for `telemetryapi` receiver

**Reply by CaptainPickles89** [reply]
I was having this issue and found that you can use the resource processor which is available within the collector layer to set this
```yaml
processors:
  resource/resource_override:
    attributes:
      - key: service.name
        value: MyAppName
        action: upsert
```
This now has my telemetry coming through with the value I want it to be instead of the name of the Lambda I am using
