### DISCUSSION TITLE
Telemetry API #310

### DISCUSSION THREAD

**Discussion by rmarasigan** [open-telemetry/opentelemetry-lambda#370] [Q&A]
I've been running some tests, but somehow, the traces' first part (_Service A_) was missing. The subsequent trace information is complete. I'm trying to send a bunch of requests (150 - 600 requests). Also, there are no error logs generated but the trace is still incomplete.

Sample Flow:
 **_Service A -> Service B -> Service C -> ... -> Service N_**

Configuration Sample:
```
exporters:
  otlp:
    retry_on_failure:
      enabled: true
      initial_interval: 10s
    tls:
      ca_file: /opt/certificate/ca.pem
      cert_file: /opt/certificate/certificate.pem
      key_file: /opt/certificate/private-key.pem
    auth:
      authenticator: oauth2client
```

Am I doing something wrong here or am I missing something?
