### ISSUE TITLE
Support for dynamic collector config

### ISSUE THREAD

**Issue by RashmiRam** [open-telemetry/opentelemetry-lambda#111]
### Usecase/Feature/Problem Statement
Collector supports attribute processors and few exporters where the config requires to be dynamic based on the use case. 

### Current approach
Include the collector config as part of the lambda function and reference the file with env var. 

#### Challenges in the current approach
- This requires changing the lambda function 
- All config(ex., exporter with headers containing any auth token, referring to AWS secrets) can't be committed to SCM. Few has to reference env var or AWS secrets.

### Proposal
I don't have a detailed proposal yet. Just wanted to check if this makes sense. 
Provision to add dynamic config with some kind of templating to generate the config when collector is instantiated.

**Comment by rijulg** [comment]
We came across this problem as well while trying to reconfigure the collector to use the OTLP exporter with other vendors. Our configuration looks like the following:

```yaml
#collector.yaml in the root directory
#Set an environemnt variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/collector.yaml'

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp/lightstep:
    endpoint: "ingest.lightstep.com:443"
    headers:
      "lightstep-access-token": "XXXXXXXX"
  otlphttp/splunk:
    traces_endpoint: "https://ingest.us1.signalfx.com/v2/trace/otlp"
    compression: gzip
    headers:
      "X-SF-Token": "XXXXXXXX"

#enables output for traces to xray
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/lightstep, otlphttp/splunk]
```
but we are unable to inject the relevant secrets i.e. API Keys from secrets manager into this config.

While committing the configuration along with our lambda code works, this raises multiple issues:
1. Any secrets get committed to git
2. Updating api keys requires changing and redeploying all the lambdas

We would prefer if there was a mechanism to obtain this configuration file, or at least the access keys from secret manager in this layer automatically.

**Comment by iulspop** [comment]
@rijulg You can reference an environment variable in a collector configuration like this:
```
  otlp/lightstep:
     endpoint: "ingest.lightstep.com:443"
     headers:
       "lightstep-access-token": "${LIGHTSTEP_ACCESS_TOKEN}"
```
See [OTel docs](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables).

I just set the environment variable of the Lambda when I create it with the CDK (using env vars from my local dev environment). The Lambda env vars are encrypted at rest by default.

If you store the API keys in Secrets Manager, you can set retrieve them and set the Lambda env var when you deploy or update the env vars after you deploy with some script.
