### ISSUE TITLE
Error on Lambda test: no such file or directory

### ISSUE THREAD

**Issue by michaelfecher** [open-telemetry/opentelemetry-lambda#3]
I'm getting an error in my Lambda when including the self-built lambda layer:
```
{
  "errorMessage": "RequestId: 16cb64d6-a350-4939-8dd8-9148f8d934f1 Error: fork/exec /opt/extensions/opentelemetry-lambda-extension: no such file or directory",
  "errorType": "Extension.LaunchError"
}
```

**Steps:**
1. Makefile build

ZIP File of step1 has the content:
```
extensions/opentelemetry-lambda-extension
```

2. Makefile publish
Layer is created in the account + region

3. adding layer to a lambda function with hello-world content with NodeJS Runtime 12
4. adding the `collector.yaml` in the root of the function
content:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

exporters:
  awsxray:
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
```
5. setting env variable:
`OPENTELEMETRY_COLLECTOR_CONFIG_FILE=/var/task/collector.yaml`

6. hit test
