### ISSUE TITLE
Question: Collector not sending data

### ISSUE THREAD

**Issue by barendb** [open-telemetry/opentelemetry-lambda#8]
Our organisation is running a few tests to see if this is a viable option, but we've run into some teething issues, the collector receives data, but none of that data is sent to exporters.

Just wondering what we can look at. We're using the following conf

```
receivers:
  otlp:
    protocols:
      grpc: # on port 55680
      http: # on port 55681

processors:
  batch:

exporters:
  otlp:
    endpoint: "https://api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "****redacted***"
      "x-honeycomb-dataset": "testing"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
```

We can see the event is received, but never sent to our exporter 

```
[opentelemetry-lambda-extension] Received event: {
	"eventType": "INVOKE",
	"deadlineMs": 1614115570609,
	"requestId": "dcaba70b-72e5-4b02-8bef-f7355fecd324",
	"invokedFunctionArn": "arn:aws:lambda:us-west-2:****redacted****:function:extention-test",
	"tracing": {
		"type": "X-Amzn-Trace-Id",
		"value": "Root=1-****redacted****;Sampled=0"
	}
}
```

**Comment by rickydua** [comment]
Tried with variant `endpoint: "api.honeycomb.io:443"`, this gives us the same result

**Comment by wangzlei** [comment]
Refer design doc, The Collector needs to remove all processors from config to keep one thread only from the receiver to the exporter. In this way, telemetry data is flushed to the backend synchronously at the end of every invocation.

**Comment by mirii1994** [comment]
I'm having the same issue, without using processors:
```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ***some webhook***
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]

```

Tried with otlp exporter and also with otlphttp exporter.
@wangzlei can you please advice?
